# Default values for iom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
downtime: true

image:
  repository: archetype-project-iom
  # Overrides the image tag whose default is the chart version.
  tag: "5.0.0"
  pullPolicy: IfNotPresent

dbaccount:
  # if enabled, dbaccount will be executed during installation process only, not on upgrade!
  enabled: true
  # options allows to set database options.
  options: "ENCODING='UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' CONNECTION LIMIT=-1 TEMPLATE=template0"
  # searchPath extends the search-path for DB objects, e.g.:
  # searchPath: "testcases"
  searchPath:
  image:
    repository: docker.tools.intershop.com/iom/intershophub/iom-dbaccount
    tag:        2.0.0
    pullPolicy: IfNotPresent
  resources: {}
  
oms:
  # public URL of IOM
  # used internally by IOM for link generation.
  publicUrl:                       http://k8s.ics.j.intershop.de
  # Shared secret for JWT creation / validation
  jwtSecret:                       length_must_be_at_least_32_chars
  # if set to true, secure flag is set to cookies. if secure flag is set, OMT
  # requires HTTPS to function properly.
  secureCookiesEnabled:            false
  
  # IOM database related settings
  db:
    name:               oms_db
    user:               oms_user
    passwd:             OmsDB
    
# Wildfly related settings
jboss:
  xaPoolsizeMin: "50"
  xaPoolsizeMax: "125"
  nodePrefix: archetype-test

# IOM logging related settings
log:
  level:
    # log-level for scripts can be one of: ERROR, WARN, INFO, DEBUG
    scripts:       INFO
    # log-level for following scopes can be one of: FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
    console:       WARN
    iom:           WARN
    hibernate:     WARN
    quartz:        WARN
    activeMQ:      WARN
    customization: DEBUG
  access:
    enabled:       true

# project related settings
project:
  envName:               ci
  importTestData:        true
  importTestDataTimeout: 300

persistence:
  provisioning: dynamic
  dynamic:
    storageClass: azurefile
    # set empty annotations to allow deletion of PV
    annotations:

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

imagePullSecrets:
  - name: intershop-pull-secret
  - name: devops-pull-secret
  
serviceAccount:
  # Specifies whether a service account should be created
  create: true

service:
  type: ClusterIP
  port: 80

postgres:
  enabled: true
  image:
    tag: "15"
  args: ["-N", "500", "-c", "max_prepared_transactions=100", "-c", "log_directory=/tmp", "-c", "log_destination=stderr,csvlog", "-c", "logging_collector=on", "-c", "log_filename=pg-G18-%Y%m%d_%H%M.log", "-c", "log_lock_waits=on", "-c", "log_min_duration_statement=500" ]
  persistence:
    enabled: false
  resources:
    requests:
      memory: "3000Mi"
      cpu: "0.75"
    limits:
      memory: "3000Mi"
      cpu: "0.75"    

mailpit:
  enabled: true
  ingress:
    enabled: false

iom-tests:
  enabled: false

# Workaround to overcome the problem with '-' in names of variables.
# The following variables do not have any impact on the configuration of ingress-nginx (except the enabled flag).
# They are provided to be used in templates.
ingress:
  enabled: true
  annotations:
    #kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  hosts:
  - host: k8s.ics.j.intershop.de
    paths:
      - path: /
        pathType: Prefix
