# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-repositories-resource
resources:
  repositories:
    - repository: IOMDevopsRepo
      type: git
      name: order-iom-partner-devops
      ref: main

trigger:
  branches:
    include:
      - '*'

# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#extend-from-a-template
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-other-repositories
extends:
  template: template.yml@IOMDevopsRepo
  parameters:
    agentPool:                          ${customerCode}-bldagnt-ubuntu-DS4_v2
    artifactsFeed:                      iom-maven-artifacts
    dockerRepoIOMServiceConnection:     docker-tools-cr
    dockerRepoIOM:                      ${intershopDockerRepo}
    acrServiceConnection:               ${projectName}-${customerCode}-acr
    acr:                                ${customerOrg}acr.azurecr.io
    projectEnvName:                     dev
